name: Pause Community Contributions

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  pause:
    if: github.repository_owner == 'exercism' # Stops this job from running on forks
    uses: exercism/github-actions/.github/workflows/community-contributions.yml@3390a06eae3295d427e35adfc15c0bf5d7f32973
    with:
      forum_category: fsharp
