name: Tools

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * * # First day of each month

permissions:
  contents: read

jobs:
  sync-labels:
    uses: ErikSchierboom/github-actions-1/.github/workflows/labels.yml@sync-labels-reusable-workflows
